async function init() {
  await customElements.whenDefined('gmp-map');

  const map = document.querySelector('gmp-map');
  const marker = document.querySelector('gmp-advanced-marker');
  const placePicker = document.querySelector('gmpx-place-picker');
  const infowindow = new google.maps.InfoWindow();

  map.innerMap.setOptions({
    mapTypeControl: false
  });

  placePicker.addEventListener('gmpx-placechange', () => {
    const place = placePicker.value;

    if (!place || !place.location) {
      window.alert(
        `No details available for input: '${place?.name || 'Unknown'}'`
      );
      infowindow.close();
      marker.position = null;
      return;
    }

    if (place.viewport) {
      map.innerMap.fitBounds(place.viewport);
    } else {
      map.center = place.location;
      map.zoom = 17;
    }

    marker.position = place.location;
    infowindow.setContent(
      `<strong>${place.displayName}</strong><br>
       <span>${place.formattedAddress}</span>`
    );
    infowindow.open(map.innerMap, marker);
  });
}

document.addEventListener('DOMContentLoaded', init);

// API integration for Railway deployment
const API_BASE_URL = 'https://your-railway-api-url.com';

async function fetchPlaceData(placeId) {
  try {
    const response = await fetch(`${API_BASE_URL}/places/${placeId}`);
    if (!response.ok) {
      throw new Error('Failed to fetch place data');
    }
    return await response.json();
  } catch (error) {
    console.error('Error fetching place data:', error);
    return null;
  }
}
